// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muvcimrhmznjkgoxzvxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11dmNpbXJobXpuamtnb3h6dnhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMTY0NTYsImV4cCI6MjA2OTc5MjQ1Nn0.rSWEIXT3Q8q7RrKGRjZiZn_H1B9pFlNzXRsz1HxTXUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});